## 배포용
#spring:
#  profiles:
#    include: oauth
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://3.20.42.141:3306/compDB?serverTimezone=UT&characterEncoding=UTF-8
#    username: comp
#    password: 1q2w3e4r!
#  jpa:
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
#server:
#  servlet:
#    session:
#      tracking-modes: cookie




#--- # set1 환경
#
#spring:
#  config:
#    activate:
#      on-profile: set1
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://3.20.42.141:3306/compDB?serverTimezone=UT&characterEncoding=UTF-8
#    username: comp
#    password: 1q2w3e4r!
#  jpa:
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
#server:
#  port: 8080
#  servlet:
#    session:
#      tracking-modes: cookie
#---
#
#--- # set2 환경
#spring:
#  config:
#    activate:
#      on-profile: set2
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://3.20.42.141:3306/compDB?serverTimezone=UT&characterEncoding=UTF-8
#    username: comp
#    password: 1q2w3e4r!
#  jpa:
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
#server:
#  port: 8081
#  servlet:
#    session:
#      tracking-modes: cookie
#---