version: '3'

services:
  springproject:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: comp-0.0.1-SNAPSHOT.jar
    image: springproject:1.0
    ports:
      - "8082:8080"
    container_name: springproject_blue